# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5dafb1544cf141c4c30ae0e9295599ec3f20bb03a8ce4a8f8ce9f85dc6ce26f75ee502a930e6c97fde4b791dfbb90433a26dc9b9dbdff94770947d10749523e

test:
  secret_key_base: 035e653aa0a355f794a9bddace76f4e1c961ab4ef0cdf5bebc3d08b8a6c2cdded6165fb30543a9d731a7b4bbb7599dc2f3740a72054e55b0743361a1237c5bb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
